@startuml
class TMP_FrameRateCounter {
    + UpdateInterval : float = 5.0f
    Awake() : void
    Start() : void
    Update() : void
    Set_FrameCounter_Position(anchor_position:FpsCounterAnchorPositions) : void
}
enum FpsCounterAnchorPositions {
    TopLeft,
    BottomLeft,
    TopRight,
    BottomRight,
}
MonoBehaviour <|-- TMP_FrameRateCounter
TMP_FrameRateCounter o-> "AnchorPosition" FpsCounterAnchorPositions
TMP_FrameRateCounter +-- FpsCounterAnchorPositions
@enduml
